version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gallery-database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  server:
    image: server
    restart: always
    environment: 
      SPRING_DATA_MONGODB_URI: mongodb://gallery:password@mongo:27017/gallery-database?authSource=gallery-database&authMechanism=SCRAM-SHA-1
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
  client:
    image: client
    ports:
      - "80:80"